#!/usr/bin/env python3

import sys

def factorize(number):
    factors = []
    for i in range(2, int(num**0.5)+1):
        if number % i == 0:
            factors.append((i, number // i))
    return factors

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: {} <file>".format(sys.argv[0]))
        sys.exit(1)

    filename = sys.argv[1]
    f = open(filename, 'r'):
        for line in f:
            number = int(line.strip())
            factorizations = factorize(number)
            for factorization in factorizations:
                print("{}={}*{}".format(number, factorization[0], factorization[1])
    f.close()
